apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-deployment
  labels:
    app: boardgame
spec:
  replicas: 5
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
      - name: boardgame
        image: bkrrajmali/boardshack:latest
        ports:
        - containerPort: 8080

----
apiVersion: v1
kind: Service
metadata:
  name: boardgame-service
spec:
  type: LoadBalancer
  selector:
    app: boardgame
  ports:
    - protocol: "TCP"
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)