apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-deployment
  labels:
    app: boardgame
spec:
  replicas: 5
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
      - name: boardgame
        image: bkrrajmali/boardshack:latest
        ports:
        - containerPort: 8080